LanguageCourses/Controllers/CourseController.cs
using LanguageCourses.Data;
using LanguageCourses.Interfaces;
using LanguageCourses.Models;
using LanguageCourses.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LanguageCourses.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CourseController(ICourseRepository courseRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _courseRepository = courseRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index()
        {
            var courses = await _courseRepository.GetAll();
            return View(courses);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var course = await _courseRepository.GetCourseByIdAsync(id);
            return View(course);
        }

        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createCourseViewModel = new CreateCourseViewModel { UserId = curUserId };
            return View(createCourseViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCourseViewModel courseVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(courseVM.Image);

                var course = new Course
                {
                    Title = courseVM.Title,
                    Description = courseVM.Description,
                    Image = result.Url.ToString(),
                    UserId = courseVM.UserId,
                    CourseCategory = courseVM.CourseCategory,
                    Address = new Address
                    {
                        City = courseVM.Address.City,
                        Street = courseVM.Address.Street,
                        State = courseVM.Address.State
                    }
                };
                _courseRepository.Add(course);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload failed!");
            }
            return View(courseVM);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var course = await _courseRepository.GetCourseByIdAsync(id);
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            if (course == null)
            {
                return View("Error");
            }
            var courseVM = new EditCourseViewModel
            {
                Title = course.Title,
                Description = course.Description,
                AddressId = course.AddressId,
                Address = course.Address,
                CourseCategory = course.CourseCategory,
                URL = course.Image,
                UserId = curUserId
            };
            return View(courseVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditCourseViewModel courseVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit course");
                return View("Edit", courseVM);
            }

            var course = await _courseRepository.GetCourseByIdAsyncNoTracking(id);

            if (course != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(course.Image);

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(courseVM);
                }

                var photo = await _photoService.AddPhotoAsync(courseVM.Image);
                var newCourse = new Course
                {
                    Id = id,
                    Title = courseVM.Title,
                    Description = courseVM.Description,
                    AddressId = courseVM.AddressId,
                    Address = courseVM.Address,
                    CourseCategory = courseVM.CourseCategory,
                    Image = photo.Url.ToString(),
                    UserId = courseVM.UserId
                };

                _courseRepository.Update(newCourse);
                return RedirectToAction("Index");
            }
            else
            {
                return View(courseVM);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var course = await _courseRepository.GetCourseByIdAsync(id);
            if (course != null)
            {
                return View(course);
            }
            else
            {
                return View("Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, Course course)
        {
            course = await _courseRepository.GetCourseByIdAsync(id);

            if (course != null)
            {
                _courseRepository.Delete(course);
                return RedirectToAction("Index");
            }
            else
            {
                return View(course);
            }
        }
    }
}

LanguageCourses/Controllers/DashboardController.cs
using LanguageCourses.Interfaces;
using LanguageCourses.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanguageCourses.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardRepository _dashboardRepository;

        public DashboardController(IDashboardRepository dashboardRepository)
        {
            _dashboardRepository = dashboardRepository;
        }
        public async Task<IActionResult> Index()
        {
            var userCourses = await _dashboardRepository.GetAllUserCourses();
            var userTeachers = await _dashboardRepository.GetAllUserTeacher();

            var dashboardViewModel = new DashboardViewModel
            {
                Courses = userCourses,
                Techers = userTeachers
            };

            return View(dashboardViewModel);
        }
    }
}

LanguageCourses/Controllers/TeacherController.cs
using LanguageCourses.Data;
using LanguageCourses.Interfaces;
using LanguageCourses.Models;
using LanguageCourses.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanguageCourses.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherRepository _teacherRepository;
        private readonly IPhotoService _photoService;
        public TeacherController(ITeacherRepository teacherRepository, IPhotoService photoService)
        {
            _teacherRepository = teacherRepository;
            _photoService = photoService;
        }

        public async Task<IActionResult> Index()
        {
            var teachers = await _teacherRepository.GetAllTeachers();
            return View(teachers);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var teacher = await _teacherRepository.GetTeacherById(id);
            if (teacher == null)
            {
                return View("Error");
            }
            return View(teacher);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateTeacherViewModel teacherVM)
        {
            if (ModelState.IsValid)
            {
                var photo = await _photoService.AddPhotoAsync(teacherVM.Image);
                var teacher = new Teacher
                {
                    Name = teacherVM.Name,
                    Surname = teacherVM.Surname,
                    Age = teacherVM.Age,
                    DetailInformation = teacherVM.DetailInformation,
                    CourseCategory = teacherVM.CourseCategory,
                    Image = photo.Url.ToString(),
                    Address = new Address
                    {
                        City = teacherVM.Address.City,
                        State = teacherVM.Address.State,
                        Street = teacherVM.Address.Street
                    }
                };
                _teacherRepository.Add(teacher);
                return RedirectToAction("Index");
            }

            else
            {
                ModelState.AddModelError("", "Photo upload failed!");
            }
            return View(teacherVM);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var teacher = await _teacherRepository.GetTeacherById(id);

            if (teacher == null)
            {
                return View("Error");
            }
            return View(teacher);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, Teacher teacher)
        {
            teacher = await _teacherRepository.GetTeacherById(id);
            if (teacher == null)
            {
                return View("Error");
            }
            _teacherRepository.Delete(teacher);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var teacher = await _teacherRepository.GetTeacherById(id);

            if (teacher == null)
            {
                return View("Error");
            }
            var teacherVM = new EditTeacherViewModel
            {
                Name = teacher.Name,
                Surname = teacher.Surname,
                Age = teacher.Age,
                AddressId = teacher.AddressId,
                Address = teacher.Address,
                URL = teacher.Image,
                CourseCategory = teacher.CourseCategory,
                DetailInformation = teacher.DetailInformation
            };
            return View(teacherVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditTeacherViewModel teacherVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit teacher");
                return View("Edit", teacherVM);
            }

            var teacher = await _teacherRepository.GetTeacherByIdNoTracking(id);
            if (teacher != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(teacher.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(teacherVM);
                }

                var photo = await _photoService.AddPhotoAsync(teacherVM.Image);
                var newTeacher = new Teacher
                {
                    Id = id,
                    Name = teacherVM.Name,
                    Surname = teacherVM.Surname,
                    DetailInformation = teacherVM.DetailInformation,
                    Image = photo.Url.ToString(),
                    CourseCategory = teacherVM.CourseCategory,
                    AddressId = teacherVM.AddressId,
                    Address = teacherVM.Address
                };
                _teacherRepository.Update(newTeacher);
                return RedirectToAction("Index");
            }
            else
            {
                return View(teacherVM);
            }
        }
    }
}

LanguageCourses/Controllers/UserController.cs
using LanguageCourses.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace LanguageCourses.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IHttpContextAccessor _contextAccessor;

        public UserController(IUserRepository userRepository, IHttpContextAccessor contextAccessor)
        {
            _userRepository = userRepository;
            _contextAccessor = contextAccessor;

        }
        public async Task<IActionResult> Index()
        {
            var id = _contextAccessor.HttpContext.User.GetUserId();
            var user = await _userRepository.GetUserById(id);

            if (user == null)
            {
                return View("Error");
            }
            return View(user);
        }

        public async Task<IActionResult> Detail(string id)
        {
            var user = await _userRepository.GetUserById(id);
            if (user == null)
            {
                return View("Error");
            }
            return View(user);
        }
    }
}

LanguageCourses/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LanguageCourses</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/LanguageCourses.styles.css" asp-append-version="true" /> *@
</head>
<body class="body">
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="~/img/svg/logo.svg" alt="logo">
                </a>
                <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavId">
                    <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" asp-action="Index" asp-controller="Home" aria-current="page">
                                Home <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Teacher" asp-action="Index">Teachers</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <form asp-area="" asp-controller="Account" asp-action="Logout">
                                    <button class="btn btn-outline-danger">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-success" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                    <div class="d-flex my-2 my-lg-0">
                        <a asp-controller="User" asp-action="Index">
                            <img src="~/img/svg/icon-user.svg" alt="user-icon">
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="footer">
        <div class="container">
            <div class="footer-text pt-5">
                <ul class="row">
                    <li class="col-3">
                        <p>Fluency is nothing more than mastering the 100 most important real-life conversations</p>
                        <ul class="social-list row">
                            <li class="col-1">
                                <a href="#">
                                    <img src="~/img/svg/Facebook.svg">
                                </a>
                            </li>
                            <li class="col-1 mx-2">
                                <a href="#">
                                    <img src="~/img/svg/LinkedIn.svg">
                                </a>
                            </li>
                            <li class="col-1 mx-2">
                                <a href="#">
                                    <img src="~/img/svg/Twitter.svg">
                                </a>
                            </li>
                            <li class="col-1 mx-2">
                                <a href="#">
                                    <img src="~/img/svg/Pinterest.svg">
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="col-3">
                        <p><strong>Speak up courses</strong></p>
                        <p class="my-0"><a>Learn english</a></p>
                        <p class="my-0"><a>Learn german</a></p>
                        <p class="my-0"><a>Learn french</a></p>
                    </li>
                    <li class="col-3">
                        <p><strong>Products</strong></p>
                        <p class="my-0"><a>Landing page</a></p>
                        <p class="my-0"><a>About us</a></p>
                        <p class="my-0"><a>Contact us</a></p>
                    </li>
                    <li class="col-3">
                        <p><strong>Contact information</strong></p>
                        <p class="my-0"><a>+32343793486</a></p>
                        <p class="my-0"><a>Info@speakup.we</a></p>
                        <p class="my-0"><a>barcelona, C/ de sardenya</a></p>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>